// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestStatistic } from "./BacktestStatistic";
import type { BacktestStatus } from "./BacktestStatus";
import type { MarketPrecision } from "./MarketPrecision";
import type { Timeframe } from "./Timeframe";

export type BacktestTask = { id: string, status: BacktestStatus, progress: number, name: string, exchange: string, symbol: string, timeframe: Timeframe, precision: MarketPrecision, statistic?: BacktestStatistic, error_message?: string, created_at: number, started_at?: number, completed_at?: number, updated_at: number, };
