// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trade } from "./Trade";

export type BacktestStatistic = { trades: Array<Trade>, initial_capital: string, total_cost: string, net_profit: string, return_percent: number, max_equity: string, max_drawdown: string, max_drawdown_percent: number, gross_profit: string, gross_loss: string, profit_factor: number, sharpe_ratio: number, total_trades: number, buy_trades: number, sell_trades: number, winning_trades: number, losing_trades: number, win_rate: number, avg_win: string, avg_loss: string, largest_win: string, largest_loss: string, };
