// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TradeType } from "./TradeType";

export type Trade = { timestamp: number, trade_type: TradeType, price: string, amount: string, fee: string, profit?: string, };
